In [1]:
import time
import argparse
import gym
import numpy as np
from stable_baselines3 import A2C
from stable_baselines3.a2c import MlpPolicy
from stable_baselines3.common.env_checker import check_env
import ray
from ray.tune import register_env
from ray.rllib.agents import ppo

from gym_pybullet_drones.utils.Logger import Logger
from gym_pybullet_drones.envs.single_agent_rl.TakeoffAviary import TakeoffAviary
from gym_pybullet_drones.utils.utils import sync, str2bool

DEFAULT_RLLIB = False
DEFAULT_GUI = True
DEFAULT_RECORD_VIDEO = False
DEFAULT_OUTPUT_FOLDER = 'results'
DEFAULT_COLAB = False

pybullet build time: May 20 2022 19:44:17


In [ ]:
env = gym.make("takeoff-aviary-v0")
print("[INFO] Action space:", env.action_space)
print("[INFO] Observation space:", env.observation_space)
check_env(env,
            warn=True,
            skip_render_check=True
            )
obs=env.reset()
done = False

while not done:
    env.render()
    action = env.action_space.sample()
    obs, reward, done, info = env.step(action)
    # if done:
    #     obs = env.reset()

In [ ]:
env = TakeoffAviary(gui=False,record=False)

for i in range(1):
    obs = env.reset()
    done = False

    while not done:
        env.render()
        action = env.action_space.sample()
        obs, reward, done, info = env.step(action)
        print(reward)
        # time.sleep(0.01)

env.close()

In [ ]:
logger = Logger(logging_freq_hz=int(env.SIM_FREQ/env.AGGR_PHY_STEPS),
                    num_drones=1,
                    output_folder='results',
                    colab=False
                    )
env = TakeoffAviary(gui=True,record=False)
obs = env.reset()
start = time.time()
for i in range(10*env.SIM_FREQ):
    action = env.action_space.sample()
    obs, reward, done, info = env.step(action)
    logger.log(drone=0,
                   timestamp=i/env.SIM_FREQ,
                   state=np.hstack([obs[0:3], np.zeros(4), obs[3:15],  np.resize(action, (4))]),
                   control=np.zeros(12)
                   )
    if i%env.SIM_FREQ == 0:
        env.render()
        print(done)
    sync(i, start, env.TIMESTEP)
    if done:
        obs = env.reset()
env.close()
logger.plot()

In [ ]:
env = TakeoffAviary(gui=True,record=False)
env.reset()

In [3]:
env = TakeoffAviary(gui=False,record=False)
# env = gym.make("takeoff-aviary-v0")
print("[INFO] Action space:", env.action_space)
print("[INFO] Observation space:", env.observation_space)
env.reset()

[INFO] BaseAviary.__init__() loaded parameters from the drone's .urdf:
[INFO] m 0.027000, L 0.039700,
[INFO] ixx 0.000014, iyy 0.000014, izz 0.000022,
[INFO] kf 0.000000, km 0.000000,
[INFO] t2w 2.250000, max_speed_kmh 30.000000,
[INFO] gnd_eff_coeff 11.368590, prop_radius 0.023135,
[INFO] drag_xy_coeff 0.000001, drag_z_coeff 0.000001,
[INFO] dw_coeff_1 2267.180000, dw_coeff_2 0.160000, dw_coeff_3 -0.110000
[INFO] Action space: Box([-1. -1. -1. -1.], [1. 1. 1. 1.], (4,), float32)
[INFO] Observation space: Box([-1. -1.  0. -1. -1. -1. -1. -1. -1. -1. -1. -1.], [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], (12,), float32)


/home/zkd/miniconda3/envs/flight/lib/python3.8/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(


array([ 0.    ,  0.    ,  0.0225,  0.    , -0.    ,  0.    ,  0.    ,
        0.    ,  0.    ,  0.    ,  0.    ,  0.    ], dtype=float32)

In [28]:
env.reset()

array([ 0.    ,  0.    ,  0.0225,  0.    , -0.    ,  0.    ,  0.    ,
        0.    ,  0.    ,  0.    ,  0.    ,  0.    ], dtype=float32)

In [23]:
# action = env.action_space.sample()
for i in range(10):
    obs, reward, done, info = env.step(np.array([0.5,0,0.5,0]))
    if done:
        print('done')
print(obs)
print('============')
print(env.pos)
print(env.vel)
print(env.rpy)
print(env.ang_v)

[ 0.          0.          0.02870958  0.          0.         -0.3052494
  0.          0.          0.04090336  0.          0.         -1.        ]
[[0.         0.         0.14354791]]
[[0.         0.         0.12271008]]
[[ 0.          0.         -0.95896927]]
[[ 0.          0.         -3.74521193]]


In [79]:
env.close()

numActiveThreads = 0
stopping threads
Thread with taskId 0 exiting
Thread TERMINATED
destroy semaphore
semaphore destroyed
destroy main semaphore
main semaphore destroyed
finished
numActiveThreads = 0
btShutDownExampleBrowser stopping threads
Thread with taskId 0 exiting
Thread TERMINATED
destroy semaphore
semaphore destroyed
destroy main semaphore
main semaphore destroyed


In [12]:
# print(env.pos)
# print(env.vel)
# print(env.rpy)
# print(env.ang_v)

env.pos=np.array([[0.5,0.5,0.5]])

In [30]:
env.DRONE_IDS

array([1])